import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { GameKitProject } from "@gamekit/schema";

export async function regenerateAssetsManifest(
  basePath: string,
  project: GameKitProject,
): Promise<void> {
  const generatedDir = join(basePath, "gamekit", "generated");
  const assetsPath = join(generatedDir, "assets.ts");
  await mkdir(generatedDir, { recursive: true });

  const entries = project.assets.map((asset) => {
    return `  "${asset.id}": require("../assets/${asset.file}")`;
  });

  const content = `/* This file is generated by GameKit CLI. */
export const gamekitAssets = {
${entries.join(",\n")}
} as const;
`;

  await writeFile(assetsPath, content);
}
