/**
 * Headless E2E pipeline (no browser): create → doctor → simulate → export bootstrap.
 * Proves the "ship a game" path without Playwright.
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { createGameFromSkill, exportProject, readScene } from "../src/project.js";
import { runDoctor } from "../src/doctor.js";
import { startEditorServer } from "../src/server.js";
import { simulateSceneSteps } from "@gamekit/runtime/simulate";

let root: string;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), `playroom-pipeline-${randomUUID()}-`));
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

describe("E2E pipeline (create → doctor → simulate → export → API)", () => {
  it("ships a platformer without manual wiring", async () => {
    const created = await createGameFromSkill(root, "platformer", {
      name: "Pipeline Demo",
      platform: "web",
    });
    expect(created.sceneId).toBe("platformer");

    const doctor = await runDoctor(root);
    expect(doctor.ok).toBe(true);
    expect(doctor.summary.errors).toBe(0);

    const scene = await readScene(root, "platformer.scene.json");
    const sim = simulateSceneSteps(scene, {
      steps: 30,
      input: { right: true, jump: false, left: false },
      runRules: true,
    });
    expect(sim.steps).toBe(30);
    expect(sim.entitySummaries.length).toBeGreaterThan(0);
    const player = sim.entitySummaries.find((e) => /player/i.test(e.name));
    expect(player).toBeDefined();
    // Moving right should change x from spawn
    if (player) {
      expect(player.position.x).not.toBe(100); // skill spawn is ~100; after motion differs or same if blocked — at least sim ran
    }
    expect(["playing", "won", "lost"]).toContain(sim.rulesOutcome ?? "playing");

    const out = join(root, "export-web");
    await exportProject(root, out, "web");
    const mainTs = await readFile(join(out, "src", "main.ts"), "utf8");
    expect(mainTs).toContain("Generated by gamekit export");
    expect(mainTs).toContain("menu.scene.json");
    expect(mainTs).toContain("platformer.scene.json");
    expect(mainTs).toContain("register(");
  });

  it("editor server serves project snapshot and doctor on a free port", async () => {
    await createGameFromSkill(root, "topdown", { name: "API Demo" });
    const handle = await startEditorServer({
      root,
      host: "127.0.0.1",
      port: 0,
    });
    try {
      const projectRes = await fetch(`${handle.url}/api/project`);
      expect(projectRes.ok).toBe(true);
      const project = (await projectRes.json()) as {
        project: { name: string; scenes: string[] };
        scenes: string[];
      };
      expect(project.project.name).toBe("API Demo");
      expect(project.scenes.some((s) => s.includes("topdown"))).toBe(true);

      const doctorRes = await fetch(`${handle.url}/api/doctor`);
      expect(doctorRes.ok).toBe(true);
      const doctor = (await doctorRes.json()) as { ok: boolean; summary: { errors: number } };
      expect(doctor.ok).toBe(true);
      expect(doctor.summary.errors).toBe(0);

      const sceneRes = await fetch(
        `${handle.url}/api/scene?file=${encodeURIComponent("topdown.scene.json")}`,
      );
      expect(sceneRes.ok).toBe(true);
      const scene = (await sceneRes.json()) as { id: string };
      expect(scene.id).toBe("topdown");
    } finally {
      await handle.close();
    }
  });
});
