import { mkdtemp, readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import {
  createEmptyScene,
  createEntity,
  createMenuScene,
  createProject,
  createSettingsScene,
  createStarterGameplayScene,
  projectToJson,
  sceneToJson,
} from "@gamekit/schema";
import {
  generateMobileApp,
  generateWebMain,
  orderSceneFiles,
  resolveTransitionMs,
  sceneFileToImportVar,
  type BootstrapInput,
} from "../src/export-bootstrap.js";
import {
  buildExportBootstrapInput,
  exportProject,
  initProject,
  writeProject,
  writeScene,
} from "../src/project.js";

describe("export-bootstrap helpers", () => {
  it("maps scene filenames to valid import identifiers", () => {
    expect(sceneFileToImportVar("menu.scene.json")).toBe("menuJson");
    expect(sceneFileToImportVar("level-1.scene.json")).toBe("level_1Json");
    expect(sceneFileToImportVar("2boss.scene.json")).toBe("scene_2bossJson");
  });

  it("orders project.scenes first then disk extras", () => {
    expect(
      orderSceneFiles(
        ["main.scene.json", "menu.scene.json"],
        ["extra.scene.json", "main.scene.json", "menu.scene.json"],
      ),
    ).toEqual(["main.scene.json", "menu.scene.json", "extra.scene.json"]);
  });

  it("converts schema transition seconds to ms", () => {
    expect(resolveTransitionMs([{ type: "fade", duration: 0.35 }])).toEqual({
      type: "fade",
      duration: 350,
    });
    expect(resolveTransitionMs([{ type: "slide", duration: 400 }])).toEqual({
      type: "slide",
      duration: 400,
    });
    expect(resolveTransitionMs(null)).toEqual({ type: "fade", duration: 250 });
  });

  it("generates web and mobile entrypoints for all scenes", () => {
    const input: BootstrapInput = {
      scenes: [
        {
          file: "menu.scene.json",
          bare: "menu",
          importVar: "menuJson",
          sceneId: "menu",
          hasPlayerController: false,
        },
        {
          file: "level-1.scene.json",
          bare: "level-1",
          importVar: "level_1Json",
          sceneId: "level-1",
          hasPlayerController: true,
        },
      ],
      activeScene: "menu.scene.json",
      transition: { type: "fade", duration: 350 },
    };

    const web = generateWebMain(input);
    expect(web).toContain('import menuJson from "../gamekit/scenes/menu.scene.json"');
    expect(web).toContain('import level_1Json from "../gamekit/scenes/level-1.scene.json"');
    expect(web).toContain('register("menu.scene.json", menuJson)');
    expect(web).toContain('register("level-1.scene.json", level_1Json)');
    expect(web).toContain("LocalStorageProvider");
    expect(web).toContain("duration: 350");
    expect(web).not.toContain("showControls");

    const mobile = generateMobileApp(input);
    expect(mobile).toContain('import menuJson from "./gamekit/scenes/menu.scene.json"');
    expect(mobile).toContain('import level_1Json from "./gamekit/scenes/level-1.scene.json"');
    expect(mobile).toContain("GAMEPLAY_SCENE_IDS");
    expect(mobile).toContain('"level-1"');
    expect(mobile).toContain("react-native-gesture-handler");
    expect(mobile).toContain("InMemoryStorage");
  });
});

describe("exportProject multi-scene bootstrap", () => {
  it("writes generated main.ts / App.tsx that import every scene", async () => {
    const root = await mkdtemp(join(tmpdir(), "gamekit-export-"));
    await initProject(root, { name: "Export Fixture" });

    // Extra custom scene with PlayerController
    const custom = createEmptyScene("Boss Fight");
    custom.id = "boss";
    const bossPlayer = createEntity("BossPlayer", { x: 0, y: 0 });
    bossPlayer.components.push({
      type: "PlayerController",
      speed: 200,
      jumpVelocity: 500,
      gravity: 1800,
    });
    custom.entities.push(bossPlayer);
    await writeScene(root, custom, "boss.scene.json");
    const project = await (await import("../src/project.js")).readProject(root);
    if (!project.scenes.includes("boss.scene.json")) {
      project.scenes.push("boss.scene.json");
    }
    await writeProject(root, project);

    const webOut = join(root, "out-web");
    await exportProject(root, webOut, "web");
    const mainTs = await readFile(join(webOut, "src", "main.ts"), "utf8");
    expect(mainTs).toContain("Generated by gamekit export");
    expect(mainTs).toContain("menu.scene.json");
    expect(mainTs).toContain("settings.scene.json");
    expect(mainTs).toContain("main.scene.json");
    expect(mainTs).toContain("boss.scene.json");
    expect(mainTs).toContain("bossJson");

    const mobileOut = join(root, "out-mobile");
    await exportProject(root, mobileOut, "mobile");
    const appTsx = await readFile(join(mobileOut, "App.tsx"), "utf8");
    expect(appTsx).toContain("Generated by gamekit export");
    expect(appTsx).toContain("boss.scene.json");
    expect(appTsx).toContain("GAMEPLAY_SCENE_IDS");
    // main + boss have PlayerController; menu/settings do not
    expect(appTsx).toContain('"main"');
    expect(appTsx).toContain('"boss"');

    // Scenes and assets are copied
    const bossCopied = await readFile(join(webOut, "gamekit", "scenes", "boss.scene.json"), "utf8");
    expect(bossCopied).toContain('"id": "boss"');
  });

  it("buildExportBootstrapInput prefers project.scenes order", async () => {
    const root = await mkdtemp(join(tmpdir(), "gamekit-boot-"));
    const gk = join(root, "gamekit");
    await mkdir(join(gk, "scenes"), { recursive: true });
    await mkdir(join(gk, "assets"), { recursive: true });
    await mkdir(join(gk, "generated"), { recursive: true });

    const project = createProject("Order Test");
    // Deliberately reverse-ish order
    project.scenes = ["main.scene.json", "settings.scene.json", "menu.scene.json"];
    project.activeScene = "menu.scene.json";
    await writeFile(join(gk, "project.json"), projectToJson(project));
    await writeFile(join(gk, "scenes", "menu.scene.json"), sceneToJson(createMenuScene("Order")));
    await writeFile(join(gk, "scenes", "settings.scene.json"), sceneToJson(createSettingsScene()));
    await writeFile(join(gk, "scenes", "main.scene.json"), sceneToJson(createStarterGameplayScene()));

    const input = await buildExportBootstrapInput(root);
    expect(input.scenes.map((s) => s.file)).toEqual([
      "main.scene.json",
      "settings.scene.json",
      "menu.scene.json",
    ]);
    expect(input.scenes.find((s) => s.file === "main.scene.json")?.hasPlayerController).toBe(true);
    expect(input.scenes.find((s) => s.file === "menu.scene.json")?.hasPlayerController).toBe(false);
  });
});
