/* Generated by gamekit export — do not edit by hand; re-export to regenerate. */
import { createGameKitGame } from "@gamekit/runtime-web";
// Subpath imports avoid pulling React Native entry points into the browser bundle.
import { SceneManager, LocalStorageProvider } from "@gamekit/runtime/manager";
import { loadScene } from "@gamekit/runtime/scene";
import type { GameKitScene, GuiComponent } from "@gamekit/schema";
import projectJson from "../gamekit/project.json";
import menuJson from "../gamekit/scenes/menu.scene.json";
import settingsJson from "../gamekit/scenes/settings.scene.json";
import mainJson from "../gamekit/scenes/main.scene.json";
import { gamekitAssets } from "../gamekit/generated/assets";

const assets = gamekitAssets as Record<string, string>;
const guiComponents = (projectJson.guiComponents ?? []) as GuiComponent[];

const scenes: Record<string, ReturnType<typeof loadScene>> = {};
function register(file: string, raw: unknown) {
  const loaded = loadScene(raw, assets);
  const bare = file.replace(/\.scene\.json$/i, "");
  scenes[file] = loaded;
  scenes[bare] = loaded;
  scenes[loaded.scene.id] = loaded;
}

register("menu.scene.json", menuJson);
register("settings.scene.json", settingsJson);
register("main.scene.json", mainJson);

const manager = new SceneManager(
  { scenes, transition: { type: "fade", duration: 350 } },
  projectJson.levels ?? [],
  new LocalStorageProvider(),
);

manager.switchScene("menu") ||
  manager.switchScene("settings") ||
  manager.switchScene("coin-rush") ||
  manager.switchScene("main");

const container = document.getElementById("game")!;
let game: ReturnType<typeof createGameKitGame> | null = null;

function mountCurrent() {
  const current = manager.getCurrentScene();
  if (!current) return;
  const scene = current.scene as GameKitScene;
  if (game) {
    game.destroy(true);
    game = null;
    container.innerHTML = "";
  }
  game = createGameKitGame({
    scene,
    assets,
    container,
    pixelArt: false,
    guiComponents,
    sceneManager: {
      switchScene: (id) => {
        const ok = manager.switchScene(id);
        if (ok) mountCurrent();
        return ok;
      },
      nextScene: () => {
        const ok = manager.nextScene();
        if (ok) mountCurrent();
        return ok;
      },
      nextLevel: () => {
        const ok = manager.nextLevel();
        if (ok) mountCurrent();
        return ok;
      },
      unlockLevel: (id) => manager.unlockLevel(id),
      completeLevel: (id) => manager.completeLevel(id),
      getState: () => ({ currentLevelId: manager.getState().currentLevelId }),
      setPersistentVar: (k, v) => manager.setPersistentVar(k, v),
      getPersistentVar: (k, d) => manager.getPersistentVar(k, d),
    },
  });
}

mountCurrent();
