export const LIBGDX_MCP_CATALOG = {
  purpose:
    "Expose the Playroom libGDX runtime (desktop LWJGL3 + Android) and host emulators to MCP. Scene JSON authoring tools remain separate; these tools talk to Gradle, the live debug HTTP agent (port 17478), adb, and xcrun simctl.",
  debugProtocol: {
    defaultPort: 17478,
    bind: "0.0.0.0",
    discovery: [
      "PLAYROOM_LIBGDX_DEBUG_URL",
      "PLAYROOM_DEBUG_PORT",
      "<libgdxRoot>/assets/playroom-debug.json",
    ],
    threadModel: "HTTP thread parses the request, Gdx.app.postRunnable hops onto the render thread, then JSON is returned. Box2D mutations therefore never run during world.step.",
    health: "GET /health",
  },
  groups: {
    gradle: [
      "project_info",
      "build",
      "compile",
      "test",
      "dependencies",
      "clean",
      "gradle_tasks",
    ],
    runtimeControl: ["run", "stop", "restart", "pause", "resume", "step_frame", "reload_scene", "get_runtime_status"],
    world: [
      "inspect_world",
      "inspect_entity",
      "spawn_entity",
      "despawn_entity",
      "set_component",
    ],
    perf: ["get_fps", "get_frame_time", "get_draw_calls", "get_triangles", "get_gl_profile"],
    graphics: [
      "list_shaders",
      "reload_shader",
      "set_render_mode",
      "capture_frame",
      "set_camera",
      "get_graphics_info",
      "list_textures",
    ],
    engine: [
      "get_application_info",
      "get_input_state",
      "inject_input",
      "get_audio_state",
      "inspect_physics",
      "set_live_gravity",
      "raycast_live",
      "list_internal_files",
      "get_preferences",
      "set_preference",
    ],
    android: [
      "list_android_devices",
      "list_android_avds",
      "start_android_emulator",
      "build_android",
      "deploy_android",
      "run_android",
      "adb_reverse",
      "adb_shell",
      "adb_input",
    ],
    ios: [
      "list_ios_devices",
      "boot_ios_simulator",
      "shutdown_ios_simulator",
      "build_ios",
      "deploy_ios",
    ],
    devicesShared: ["capture_device_screen", "get_device_logs"],
  },
  notInRuntime: {
    hexTerritory: [
      "create_hex",
      "create_region",
      "set_hex_owner",
      "get_hex_owner",
      "highlight_region",
      "simulate_attack",
      "generate_world_chunk",
      "load_h3_region",
      "inspect_territory",
      "spawn_building",
    ],
    reason:
      "Playroom's libGDX runtime is a 2D ECS scene loader (Transform/Sprite/Box2D), not an H3 hex-strategy engine. Those APIs are not implemented.",
  },
  collisions: {
    remove_entity:
      "Already registered as a scene-JSON editor tool. Live-world deletion is despawn_entity.",
    add_entity: "Scene-JSON create. Live spawn is spawn_entity.",
    upsert_component: "Scene-JSON merge. Live mutation is set_component.",
  },
  iosGap:
    "templates/libgdx-game has core + lwjgl3 + android only. There is no RoboVM/iOS Gradle module, so build_ios/deploy_ios return a structured gap. Simulator listing/boot/screenshot still work on macOS.",
  androidNotes: {
    applicationId: "com.playroom.game",
    activity: "com.playroom.runtime.android.AndroidLauncher",
    debugPort: "The game binds 17478 on the device. run_android runs adb reverse tcp:17478 tcp:17478 so MCP on the host can reach it.",
  },
} as const;
