import { existsSync } from "node:fs";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createStarterGameplayScene, createProject, projectToJson, sceneToJson } from "@gamekit/schema";
import { detectKmpProject, type KmpProjectInfo } from "./kmp-detector.js";
import { generateAssetRegistry, getGameKitRoot } from "./project.js";

export interface AdoptKmpOptions {
  name?: string;
  sharedSourceDir?: string;
  patchGradle?: boolean;
  createLaunchers?: boolean;
  onProgress?: (message: string) => void;
}

export interface AdoptKmpResult {
  success: boolean;
  projectInfo: KmpProjectInfo;
  injectedRuntimeDir: string;
  gamekitDir: string;
  patchedFiles: string[];
  warnings: string[];
  instructions: string[];
}

function getPlayroomRoot(): string {
  return fileURLToPath(new URL("../../..", import.meta.url));
}

/**
 * Automatically adopt and inject Playroom LibGDX / Kotlin Multiplatform runtime
 * and assets into an existing Gradle or KMP project.
 */
export async function adoptKmpProject(
  root: string,
  options: AdoptKmpOptions = {}
): Promise<AdoptKmpResult> {
  const targetRoot = resolve(root);
  const info = await detectKmpProject(targetRoot);
  const warnings: string[] = [];
  const patchedFiles: string[] = [];
  const instructions: string[] = [];

  const projectName = options.name?.trim() || basename(targetRoot) || "Playroom KMP Game";
  options.onProgress?.(`Inspecting project structure at ${targetRoot}…`);

  // Step 1: Resolve target source directory for Playroom runtime
  let targetSourceDir = options.sharedSourceDir;
  if (!targetSourceDir) {
    if (info.sharedModule) {
      targetSourceDir = info.sharedModule.sourceDir;
    } else {
      // Default to shared/src/commonMain/kotlin
      targetSourceDir = join(targetRoot, "shared", "src", "commonMain", "kotlin");
    }
  }

  const playroomRuntimeDest = join(targetSourceDir, "com", "playroom", "runtime");
  options.onProgress?.(`Injecting Playroom runtime to ${playroomRuntimeDest}…`);
  await mkdir(playroomRuntimeDest, { recursive: true });

  // Step 2: Copy runtime template files
  const kmpTemplateCore = join(getPlayroomRoot(), "templates", "libgdx-kmp-game", "core", "src", "main");
  const kotlinTemplateCore = join(getPlayroomRoot(), "templates", "libgdx-kotlin-game", "core", "src", "main");
  const templateCore = existsSync(kmpTemplateCore) ? kmpTemplateCore : kotlinTemplateCore;

  if (existsSync(templateCore)) {
    // Copy java/kotlin runtime files into target
    const ktSrc = join(templateCore, "kotlin", "com", "playroom", "runtime");
    const javaSrc = join(templateCore, "java", "com", "playroom", "runtime");

    if (existsSync(ktSrc)) {
      await cp(ktSrc, playroomRuntimeDest, { recursive: true });
    }
    if (existsSync(javaSrc)) {
      await cp(javaSrc, playroomRuntimeDest, { recursive: true });
    }
    patchedFiles.push(playroomRuntimeDest);
  } else {
    warnings.push("Playroom runtime template core directory was not found; skipped runtime files copy.");
  }

  // Step 3: Set up GameKit folders and initial scenes
  options.onProgress?.("Initializing gamekit/ scenes & assets registry…");
  const gamekitRoot = getGameKitRoot(targetRoot);
  const scenesRoot = join(gamekitRoot, "scenes");
  const assetsRoot = join(gamekitRoot, "assets");
  const generatedRoot = join(gamekitRoot, "generated");

  await mkdir(scenesRoot, { recursive: true });
  await mkdir(assetsRoot, { recursive: true });
  await mkdir(generatedRoot, { recursive: true });

  const projectJsonPath = join(gamekitRoot, "project.json");
  if (!existsSync(projectJsonPath)) {
    await writeFile(projectJsonPath, projectToJson(createProject(projectName)));
    patchedFiles.push(projectJsonPath);
  }

  const mainScenePath = join(scenesRoot, "main.scene.json");
  if (!existsSync(mainScenePath)) {
    await writeFile(mainScenePath, sceneToJson(createStarterGameplayScene()));
    patchedFiles.push(mainScenePath);
  }

  await generateAssetRegistry(targetRoot, "libgdx");

  // Step 4: Patch or generate Gradle helper configuration
  const shouldPatch = options.patchGradle ?? true;
  if (shouldPatch) {
    options.onProgress?.("Configuring Gradle dependencies and asset paths…");
    const helperGradleFile = info.buildScriptType === "kts" ? "gamekit.gradle.kts" : "gamekit.gradle";
    const helperPath = join(targetRoot, helperGradleFile);

    const helperContent =
      info.buildScriptType === "kts"
        ? `// Generated by Playroom GameKit - Include in your build.gradle.kts
val gdxVersion by extra("1.13.1")
val ktxVersion by extra("1.13.1-b1")

repositories {
    mavenCentral()
    maven { url = uri("https://s01.oss.sonatype.org") }
    google()
}

// Dependencies for Playroom runtime:
// implementation("com.badlogicgames.gdx:gdx:$gdxVersion")
// implementation("com.badlogicgames.gdx:gdx-box2d:$gdxVersion")
// implementation("io.github.libktx:ktx-app:$ktxVersion")
// implementation("io.github.libktx:ktx-graphics:$ktxVersion")
// implementation("io.github.libktx:ktx-box2d:$ktxVersion")
`
        : `// Generated by Playroom GameKit - Include in your build.gradle
ext {
    gdxVersion = '1.13.1'
    ktxVersion = '1.13.1-b1'
}

repositories {
    mavenCentral()
    maven { url 'https://s01.oss.sonatype.org' }
    google()
}
`;
    await writeFile(helperPath, helperContent);
    patchedFiles.push(helperPath);
  }

  // Step 5: Generate launch helper snippet if desktop module is detected
  if (options.createLaunchers ?? true) {
    const desktopTarget = info.desktopModule?.sourceDir ?? (info.sharedModule ? join(targetRoot, "desktopApp", "src", "jvmMain", "kotlin") : undefined);
    if (desktopTarget && existsSync(desktopTarget)) {
      const launcherPath = join(desktopTarget, "PlayroomLauncher.kt");
      if (!existsSync(launcherPath)) {
        const launcherContent = `package com.playroom.runtime.launcher

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration
import com.playroom.runtime.GameKitGame

object PlayroomLauncher {
    @JvmStatic
    fun main(args: Array<String>) {
        val config = Lwjgl3ApplicationConfiguration().apply {
            setTitle("${projectName}")
            setWindowedMode(480, 800)
            useVsync(true)
            setForegroundFPS(60)
        }
        Lwjgl3Application(GameKitGame(), config)
    }
}
`;
        await writeFile(launcherPath, launcherContent);
        patchedFiles.push(launcherPath);
      }
    }
  }

  instructions.push("✔ Playroom GameKit runtime injected into your project.");
  instructions.push("✔ Game scenes, assets, and rules configured in ./gamekit/");
  instructions.push("✔ Run 'pnpm gamekit editor' to start visually designing levels.");

  return {
    success: true,
    projectInfo: info,
    injectedRuntimeDir: playroomRuntimeDest,
    gamekitDir: gamekitRoot,
    patchedFiles,
    warnings,
    instructions,
  };
}
